<a href="https://colab.research.google.com/github/shiva561/PyTorchLearnings/blob/main/tensor_ops_ipnyb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
my_torch=torch.arange(10)
my_torch


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
my_torch=my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
my_torch2=torch.arange(10)
my_torch2=my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
my_torch5=torch.arange(10)
my_torch5
my_torch5=my_torch5.view(2,5)
my_torch5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
#Change original torch
my_torch6=my_torch5.reshape(2,5)
my_torch6
my_torch5[1]=6789
my_torch6

tensor([[   0,    1,    2,    3,    4],
        [6789, 6789, 6789, 6789, 6789]])

In [17]:
#changing values in Torch
my_torch7=torch.arange(10);
my_torch8=my_torch7.reshape(2,5)
my_torch7[2]=45
my_torch8

tensor([[ 0,  1, 45,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [21]:
#Slices
#Allow grab a section of Tensor
my_torch9=torch.arange(10)
my_torch9
my_torch9[7]


tensor(7)